Vagrant.configure("2") do |config|
  config.vm.box = "bento/oracle-7"

  config.vm.provision "shell", inline: "Started by vagrant"

  config.vm.define :ansible do |ansible|
    ansible.vm.network "private_network", ip: "192.168.99.102"
  end
end
